apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d

        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "1180"  # Изменяем порт, чтобы не конфликтовать с nginx
            - name: HTTPS_PORT
              value: "11443"  # Изменяем HTTPS порт
          ports:
            - containerPort: 1180
              name: http
            - containerPort: 11443
              name: https
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
          # Добавляем команду для правильного запуска
          command: ["/bin/sh"]
          args: ["-c", "httpd -p ${HTTP_PORT} -h /usr/share/nginx/html"]

      volumes:
        - name: web-content
          configMap:
            name: web-content
        - name: nginx-config
          configMap:
            name: nginx-config