---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.75.97
      ansible_user: centos
      ansible_ssh_private_key_file: "~/.ssh/id_centos_vm"
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.67.184
      ansible_user: centos
      ansible_ssh_private_key_file: "~/.ssh/id_centos_vm"