---
- name: Тест модуля из коллекции
  hosts: localhost
  tasks:
    - name: Создать файл через модуль из коллекции
      my_own_namespace.yandex_cloud_elk.create_file:
        path: /tmp/test_collection.txt
        content: "Привет из коллекции!"
      register: result

    - name: Показать результат
      debug:
        var: result