---
all:
  hosts:
    nexus-01:
      ansible_host: 62.84.122.148
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
    ansible_ssh_private_key_file: "~/.ssh/id_centos_vm"
