apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: writer
        image: "{{ .Values.writer.image.repository }}:{{ .Values.writer.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $(date) >> /shared/data.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
      - name: reader
        image: "{{ .Values.reader.image.repository }}:{{ .Values.reader.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["tail -f /shared/data.txt"]
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
      volumes:
      - name: shared-storage
        emptyDir: {}
